### ISSUE TITLE
ModuleNotFoundError: No module named '_pymp3_c'

### ISSUE THREAD

**Issue by micpst** [michaelboulton/python_mp3_decoder#2]
Hi,
I managed to compile your package, I have a compilation in my environment, but when importing the `Decoder` there is an error, saying there is no module `_pymp3_c` even though it looks like it is in its place.

My env:
- python 3.7.8
- swig 3.0.12

Below, I send you screens with error message and environment structure:
![project](https://user-images.githubusercontent.com/47692610/88180024-03f1e300-cc2d-11ea-8b43-27304976f774.PNG)
![error](https://user-images.githubusercontent.com/47692610/88180045-0ce2b480-cc2d-11ea-9cd2-ba5ccdf38f2f.PNG)

**Comment by openedhardware** [comment]
I am getting the exact same error on Raspberry Pi:
```
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    from pymp3decoder import Decoder
  File "/usr/local/lib/python3.7/dist-packages/pymp3decoder-0.0.1-py3.7-linux-armv7l.egg/pymp3decoder/__init__.py", line 1, in <module>
    import pymp3_c
ModuleNotFoundError: No module named 'pymp3_c'
```

**Comment by el07694** [comment]
Same error

**Comment by el07694** [comment]
I found a solution for Linux:

Copy /usr/local/lib/python3.7/dist-packages/pymp3decoder-0.0.1-py3.7-linux-armv7l.egg/pymp3decoder/py_mp3.py **contents** to the top of /usr/local/lib/python3.7/dist-packages/pymp3decoder-0.0.1-py3.7-linux-armv7l.egg/pymp3decoder/__init__.py file and delete from this file the import.

Also change in two seperate times the py_mp3.<some_method> to <some_method>

Hope that helps.
